name: Deploy SSO to Staging VPS

on:
  push:
    branches:
      - staging
    # Deploy hanya akan berjalan jika ada perubahan pada folder BE, FE, atau docker-compose.yml
    paths:
      - "BE/**"
      - "FE/**"
      - "docker-compose.yml"

jobs:
  deploy:
    name: Deploy to Staging VPS
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_VPS_HOST }}
          username: ${{ secrets.STAGING_VPS_USERNAME }}
          key: ${{ secrets.STAGING_VPS_SSH_KEY }}
          port: ${{ secrets.STAGING_VPS_PORT }} # Biasanya 22
          script: |
            APP_DIR="/home/deploy/apps/sso-staging"
            REPO_URL="https://github.com/ac4bfg/sso.git"

            # 1. Cek folder staging
            if [ ! -d "$APP_DIR/.git" ]; then
              echo "Folder Staging tidak ditemukan, melakukan clone..."
              mkdir -p /home/deploy/apps
              cd /home/deploy/apps
              git clone -b staging $REPO_URL sso-staging
              cd sso-staging
            else
              echo "Folder Staging ditemukan, melakukan pull..."
              cd $APP_DIR
              git fetch --all
              git reset --hard origin/staging
            fi

            # 2. Disk Management
            docker system prune -f

            # 3. Restart
            docker-compose up -d --build

            # 4. Cleanup
            docker image prune -f
            echo "Staging Deployment berhasil!"
